### ISSUE TITLE
Change Navbar dropdown menu text colour

### ISSUE THREAD

**Issue by junhyap** [codersforcauses/starick#132]
## Basic Information
Currently the navbar dropdown menu has a white text colour on top of a white background, this results in poor visibility

![image](https://github.com/codersforcauses/starick/assets/6574274/b8c12cd7-10f6-4142-8e5a-cf302bffe03b)

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I was able to reproduce this issue and I tried to make some changes too so that the text in submenu is readable.
So, after changing the background color of dropdown menu items, the dropdown menu looks something like this:

![image](https://github.com/codersforcauses/starick/assets/31406633/71e0f447-3261-4a73-af38-3ebb0038152c)

Do you think this color looks fine or should I make any other changes?
Let me know your thoughts on the same.
Sincere apologies if at all you find any mistakes during this implementation.

Thanks and Regards,
Mohit Kambli

**Comment by seraph1201** [comment]
made redundant due to [issue 71](https://github.com/codersforcauses/starick/issues/71)
